name: Release Docker Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta web
        id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository }}-web
            name=githubyumao/mcsmanager-web

      - name: Docker meta daemon
        id: meta_daemon
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository }}-daemon
            name=githubyumao/mcsmanager-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Web
        uses: docker/build-push-action@v5
        with:
          file: dockerfile/web.dockerfile
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}

      - name: Build and Push Daemon
        uses: docker/build-push-action@v5
        with:
          file: dockerfile/daemon.dockerfile
          push: true
          tags: ${{ steps.meta_daemon.outputs.tags }}
          labels: ${{ steps.meta_daemon.outputs.labels }}
